piVersion: apps/v1
kind: Deployment
metadata:
  name: date-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: date-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: date-app
    spec:
      containers:
      - name: date-container
        image: date:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          failureThreshold: 10
          periodSeconds: 10